services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CoopTilleuls\MigrationBundle\E2e\LegacyBundle\:
        resource: '%kernel.project_dir%/LegacyBundle/{Loader,Transformer}'
        bind:
            $registry: '@doctrine'

    FeatureContext:
        class: FeatureContext
        public: true
        arguments: ['@doctrine']

    LoaderContext:
        class: LoaderContext
        public: true
        arguments: ['@doctrine', '@coop_tilleuls_migration.command.load']

    TransformerContext:
        class: TransformerContext
        public: true
        arguments: ['@doctrine']
